# Ex 1 — Working with NumPy and Pandas

**Scenario:** Manufacturing Quality Control  
**Reg No:** URK24CS1021

### NumPy

In [1]:
import numpy as np
np.random.seed(1021)

# hourly defect rates for a full day (24 values, 0.1 - 5.0 %)
defects = np.round(np.random.uniform(0.1, 5.0, 24), 2)
defects

array([3.53, 4.37, 3.62, 1.19, 4.39, 1.04, 3.72, 2.2 , 0.89, 3.59, 3.27,
       2.75, 3.3 , 0.76, 1.44, 4.78, 1.64, 2.29, 4.14, 1.09, 2.46, 2.69,
       4.12, 1.79])

In [2]:
# defect rate at the 12th hour
defects[12]

np.float64(3.3)

In [3]:
# night shift runs 20:00 to 06:00, so it wraps past midnight
night = np.concatenate((defects[20:], defects[:7]))
night

array([2.46, 2.69, 4.12, 1.79, 3.53, 4.37, 3.62, 1.19, 4.39, 1.04, 3.72])

In [4]:
# 3 shifts of 8 hours each
shifts = defects.reshape(3, 8)
shifts

array([[3.53, 4.37, 3.62, 1.19, 4.39, 1.04, 3.72, 2.2 ],
       [0.89, 3.59, 3.27, 2.75, 3.3 , 0.76, 1.44, 4.78],
       [1.64, 2.29, 4.14, 1.09, 2.46, 2.69, 4.12, 1.79]])

In [5]:
# hours where defects went above 3%
for hour, rate in enumerate(defects):
    if rate > 3:
        print("hour", hour, "->", rate, "%")

hour 0 -> 3.53 %
hour 1 -> 4.37 %
hour 2 -> 3.62 %
hour 4 -> 4.39 %
hour 6 -> 3.72 %
hour 9 -> 3.59 %
hour 10 -> 3.27 %
hour 12 -> 3.3 %
hour 15 -> 4.78 %
hour 18 -> 4.14 %
hour 22 -> 4.12 %


In [6]:
# pair each hour's defects with a temperature reading
temp = np.round(np.random.uniform(18, 30, 24), 1)
combined = np.vstack((defects, temp))
combined

array([[ 3.53,  4.37,  3.62,  1.19,  4.39,  1.04,  3.72,  2.2 ,  0.89,
         3.59,  3.27,  2.75,  3.3 ,  0.76,  1.44,  4.78,  1.64,  2.29,
         4.14,  1.09,  2.46,  2.69,  4.12,  1.79],
       [27.9 , 20.  , 19.7 , 26.6 , 27.2 , 24.8 , 19.  , 22.  , 26.1 ,
        19.7 , 22.2 , 22.4 , 27.  , 25.8 , 18.4 , 20.9 , 29.4 , 28.  ,
        20.8 , 28.  , 25.6 , 18.4 , 20.7 , 19.  ]])

In [7]:
s1, s2, s3 = np.split(defects, 3)
print("shift 1:", s1)
print("shift 2:", s2)
print("shift 3:", s3)

shift 1: [3.53 4.37 3.62 1.19 4.39 1.04 3.72 2.2 ]
shift 2: [0.89 3.59 3.27 2.75 3.3  0.76 1.44 4.78]
shift 3: [1.64 2.29 4.14 1.09 2.46 2.69 4.12 1.79]


In [8]:
# anything above 4% counts as critical
defects[defects > 4]

array([4.37, 4.39, 4.78, 4.14, 4.12])

In [9]:
np.sort(defects)

array([0.76, 0.89, 1.04, 1.09, 1.19, 1.44, 1.64, 1.79, 2.2 , 2.29, 2.46,
       2.69, 2.75, 3.27, 3.3 , 3.53, 3.59, 3.62, 3.72, 4.12, 4.14, 4.37,
       4.39, 4.78])

In [10]:
# acceptable quality is between 0.5 and 1.5%
defects[(defects >= 0.5) & (defects <= 1.5)]

array([1.19, 1.04, 0.89, 0.76, 1.44, 1.09])

### Pandas

In [11]:
import pandas as pd

products = ["Widget A", "Widget B", "Gadget"]
pd.Series(products)

0    Widget A
1    Widget B
2      Gadget
dtype: object

In [12]:
data = {"Product": ["Tool X", "Tool Y"], "Tolerance": [0.1, 0.2]}
df = pd.DataFrame(data)
df

,Product,Tolerance
0,Tool X,0.1
1,Tool Y,0.2
